safe: true
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "slate"
      title: ""
      author: "John Casey"
  - 
    scope:
      path: "user"
    values:
      nav: "Users"
  - 
    scope:
      path: "dev"
    values:
      nav: "Developers"
  - 
    scope:
      path: "ref"
    values:
      nav: "Reference"

title: "AProx Artifact Repository"
siteTitle: "Commonjava"
projectTitle: "AProx"
tagline: "Management Platform for Maven-Style Artifacts and Repositories"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

markdown: kramdown
