safe: true
defaults:
  - scope:
      path: ""
    values:
      layout: "slate"
      title: ""
      author: "John Casey"
  - scope:
      path: "user"
    values:
      nav: "user"
      breadcrumbs:
      - href: "../index.html"
        title: "Top"
  - scope:
      path: "dev"
    values:
      nav: "dev"
      breadcrumbs:
      - href: "../index.html"
        title: "Top"
  - scope:
      path: "user/addons"
    values:
      nav: "user"
      breadcrumbs:
      - href: "../index.html"
        title: "Add-Ons"
  - scope:
      path: "user/addons/depgraph"
    values:
      nav: "user"
      breadcrumbs:
      - href: "../index.html"
        title: "Add-Ons"
      - href: "index.html"
        title: "Depgraph Contents"
  - scope:
      path: "user/addons/depgraph/features"
    values:
      nav: "user"
      breadcrumbs:
      - href: "../../index.html"
        title: "Add-Ons"
      - href: "../index.html"
        title: "Depgraph Contents"
      - href: "../features.html"
        title: "Depgraph Features"

title: "Indy Artifact Management Platform"
siteTitle: "Commonjava"
projectTitle: "Indy"
tagline: "Management Platform for Artifacts and Repositories"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

gems:
  - jemoji
  - kramdown

markdown: kramdown
