safe: true
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "slate"
      title: ""
      author: "John Casey"
  - 
    scope:
      path: "docs"
    values:
      nav: "Documentation"

siteTitle: "Commonjava"
projectTitle: "AProx"
tagline: "Management Platform for Maven-Style Artifacts and Repositories"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
