safe: true
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "slate"
      title: ""
  - 
    scope:
      path: "docs"
    values:
      nav: "Documentation"

siteTitle: "Commonjava"
projectTitle: "AProx"
tagline: "Management Platform for Maven-Style Artifacts and Repositories"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org