# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Merge / Push Build

on: [push]

jobs:
  build-on-push:

    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Echo github context
      run: echo ${{ github }}

    - name: Set up JDK
      if: ${{ github.base_ref == 'maint' }}
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Set up JDK
      if: ${{ github.base_ref == 'maint' }}
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v14
      if: ${{ github.event.repository.fork == false }}
      with:
        repositories: '[{ "id": "sonatype", "url": "https://oss.sonatype.org/content/repositories/snapshots/", "releases": {"enabled": "false"}, "snapshots": {"enabled": "true" }}]'
        servers: '[{ "id": "sonatype", "username": "${{ secrets.SONATYPE_BOT_USERNAME}}", "password": "${{ secrets.SONATYPE_BOT_TOKEN}}" }]'

    - name: "Maven Build"
      run: mvn -B -e -Prun-its verify
